apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: sabb-repo-root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
   repo: https://github.com/SumethMK/acm.git
   revision: HEAD
   branch: main
   dir: test
   auth: none