apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AsmIngressgatewayLabel
metadata:
  name: asm-policy-v0.0.1-asm-ingressgateway-label
  labels:
    policycontroller.gke.io/bundleName: asm-policy-v0.0.1
  annotations:
    policycontroller.gke.io/constraintData: |
      "{
        bundleName: 'asm-policy-v0.0.1',
        bundleDisplayName: 'Anthos Service Mesh v0.0.1',
        bundleLink: 'https://cloud.google.com/anthos-config-management/docs/how-to/using-asm-security-policy',
        bundleVersion: '202209.0',
        bundleDescription: 'Use the ASM Policy v0.0.1 policy bundle with Anthos Policy Controller to evaluate the compliance of your clusters running Anthos Service Mesh against service mesh security best practices.',
        controlNumbers: '[1.1.1]',
        severity: 'UNASSIGNED',
        description: 'Enforce the istio ingressgateway label usage only on ingressgateway pods.',
        remediation: 'Remove istio:ingressgateway label from the non ingressgateway pods.',
        minimumTemplateLibraryVersion: '1.11.2'
      }"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod